name: CI


on:
  push:
  pull_request:

# This job installs dependencies, build the site, and pushes it to `gh-pages``
jobs:
  test:
    #runs-on: [ubuntu-latest, macOS-latest]  # TODO Add check for macOS
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install Conda
      uses: s-weigand/setup-conda@v1
    - name: Install LaTeX
      run: |
        sudo apt-get update
        #LaTeX packages
        sudo apt-get install -y texlive-latex-extra
        sudo apt-get install -y texlive-xetex
        sudo apt-get install texlive-bibtex-extra biber
        sudo apt-get install -y texlive-lang-greek
        sudo apt-get install -y latexmk
        sudo apt-get install lmodern
        sudo apt-get install texlive-fonts-extra
    - name: Check LaTeX compiles
      run: |
        cd tex; xelatex -interaction=nonstopmode -shell-escape main.tex
    - name: Validate notebooks
      run: |
        python -m pip install nbval pytest
        python -m pytest -vv --nbval --current-env
